### ISSUE TITLE
Sort by similarity

### ISSUE THREAD

**Issue by mzur** [biigle/largo#125]
In #120 sorting by outliers was implemented. @dlangenk suggested that we should implement sorting by similarity, too (like in MAIA). In contrast to the MAIA UI, we could add this as another option to the sorting tab. it could work like this:

- User selects "similarity" from the sorting tab
- The sorting tab list item shows "please select a reference patch"
- The user clicks on a patch
- The patch is used as a reference (shown similarly than in MAIA) and the remaining patches are sorted by similarity to the reference

**Comment by agnanas** [comment]
I am very much looking forward to this feature. Would be greatly useful :)
