### ISSUE TITLE
Feature vectors for tiled images

### ISSUE THREAD

**Issue by mzur** [biigle/largo#132]
Currently, the ProcessAnnotatedFile job cannot handle feature vectors for tiled images. In these cases, crops have to be generated that are passed on to the Python script. The python script (probably) cannot read the large image itself.

**Comment by dlangenk** [comment]
There is pyvips which can also handle any image, but installation may be tricky. Couldn't we also take the image tiles and work with these?

**Comment by mzur** [comment]
pyvips would do the same that I would do with Vips in PHP. And I don't think working with the tiles would be easier to implement. Also, they are stored as lossy JPEG and I would prefer a PNG for the feature vectors.

If you want to think about BIIGLE problems you could help me with ideas to make generating feature vectors faster :smiley: This could also improve the situation with Magic SAM. If you want, we could talk about this sometime.

**Comment by dlangenk** [comment]
Is there a python script that I can optimize? But we can talk about that tomorrow or sometime if you like.
