### ISSUE TITLE
Chunk huge database inserts

### ISSUE THREAD

**Issue by mzur** [biigle/largo#76]
We got the error `General error: 7 number of parameters must be between 0 and 65535 (SQL: insert into "image_annotation_labels" ("annotation_id", "confidence", "created_at", "label_id", "updated_at", "user_id")` which means that more than 10000 annotations should be changed in a single request. Chunk this insert ([here](https://github.com/biigle/largo/blob/f12e10b3c774b75ec3cf95c696dbd17701498a3e/src/Jobs/ApplyLargoSession.php#L238)) to 5000 annotations per call. Also look for other places that may run into this error.

**Comment by dlangenk** [comment]
That was me 🙈  with a Largo change that label request.

**Comment by mzur** [comment]
Should I run these requests again after the fix or should I dismiss them?

**Comment by dlangenk** [comment]
Dismiss it. I chunked it manually. The original request was at project level. I now do it volume-wise.

**Comment by mzur** [comment]
Ok
