### ISSUE TITLE
Show complete count of annotations at each label

### ISSUE THREAD

**Issue by aburfeid** [biigle/largo#98]
This is not prioritary, but a nice-to-have. When working on LARGO, it would be very helpful to have a count of the number of individual labels attached to each label (s. attachment). This way the need to have two browser tabs open to follow the own annotations would disappear. 
![Biigle idea_Phillip](https://user-images.githubusercontent.com/102722054/184833015-b38b1668-3f5c-412e-8f1e-13d6382adf05.png)

Thanks!

**Comment by mzur** [comment]
Nice idea, thanks! Maybe this could be opt-in for performance reasons and to keep the UI simple.

**Comment by mzur** [comment]
Continued in https://github.com/biigle/largo/issues/170.
